name: Android CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  android-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2.6.0

      - name: Setup JAVA 
        uses: actions/setup-java@v3
        with:
         java-version: '17'
         distribution: 'temurin'
         cache: cd src/OOPsIPushedToMain/gradle
          
      - name: Cache Gradle and wrapper
        uses: actions/cache@v2
        with:
          path: |
            ~/src/OOPsIPushedToMain/.gradle/caches
            ~/.src/OOPsIPushedToMain/gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
      
      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          script: ./gradlew connectedAndroidTest

    # Navigate to the Android app directory
    # - name: Grant execute permission for gradlew
    #   run: cd src/OOPsIPushedToMain/ && chmod +x gradlew
    # - name: Build with Gradle
    #   run: cd src/OOPsIPushedToMain/ && ./gradlew build
    # - name: Run Unit Tests
    #   run: cd src/OOPsIPushedToMain/ && ./gradlew test "com.oopsipushedtomain.FirebaseAccessUnitTest"
